package sriracha.frontend.android;

import android.graphics.*;

import java.util.*;

/**
 * Static class used to generate colors for the results viewer.
 * Different plots on the graph are colored differently for easy differentiation.
 * This class simply generates a bunch of colors the first time it is queried.
 * The colors are generated by simple hue rotation.
 * A "secondary" list of colors is also generated, matching the hue of the primary
 * list, but with lower saturation. This is currently used for the imaginary 
 * component of a plot with both real and imaginary curves, while the real curve
 * has the fully-saturated color.
 */
public class Colors
{
    private static ArrayList<Integer> colors;
    private static ArrayList<Integer> desaturatedColors;

    public static void init()
    {
        colors = new ArrayList<Integer>();
        desaturatedColors = new ArrayList<Integer>();

        for (float hue = 0; hue < 360; hue += 60)
        {
            colors.add(Color.HSVToColor(new float[]{hue, 1, 1}));
        }
        for (float hue = 0; hue < 360; hue += 60)
        {
            desaturatedColors.add(Color.HSVToColor(new float[]{hue, 0.5f, 1}));
        }
    }

    public static int get(int index)
    {
        if (colors == null)
            init();

        index %= colors.size();
        return colors.get(index);
    }

    public static int getSecondary(int index)
    {
        if (desaturatedColors == null)
            init();

        index %= desaturatedColors.size();
        return desaturatedColors.get(index);
    }
}
